baseurl = "https://newschematic.org/"
title = "New Schematic"
languageCode = "en-us"
theme = "hugo-goa"
footnoteReturnLinkContents = "↩"
enableEmoji = true

author = "Chris Boette"
copyright = "Chris Boette, CC by-sa-nc"
enableRobotsTXT = true

[params]
  author = "Chris Boette"
  intro = "Software Engineer, with a focus on Web"
  authorImage = "me.jpg"
  description = "Like the smell of rain on a summer day: coding"
  dateFormat = "Jan 2, 2006"
  colortheme = "light"

[params.meta]
  description = "Online portfolio and blag for Chris Boette"
  keywords = "Chris Boette, Boette, developer, software engineer, ruby, ruby on rails, javascript, typescript, web app dev, web development, MakerSquare, online portfolio, portfolio, Entertainment Technology Center, graduate"
  monetization = "$coil.xrptipbot.com/zP3gu5RkRVSdjBhe_fu3XA"

[params.social]
  github = "chrisbodhi"
  linkedIn = "chrisboette"
  twitter = "chrisbodhi"
  stackoverflow = "2276791/yossarian"

[params.extra]
  poweredBy = true
  highlightJS = true
  socialmarkup = true
  rss = true # Display next to social icons
  displayrssicon = false # Hide in footer

[[menu.main]]
  name = "now"
  weight = 100
  identifier = "now"
  url = "/now"
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  weight = 100
  identifier = "projects"
  url = "/projects/"
[[menu.main]]
  name = "resume"
  weight = 100
  identifier = "resume"
  url = "/resume"
[[menu.main]]
  name = "talks"
  weight = 100
  identifier = "talks"
  url = "/talks/"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
    [markup.goldmark.renderer]
      unsafe = true
